var html= '<div class="card-post">'
    + '<div class="row">'
      + '<div class="col-xs-3 col-sm-2">'
      + '<a href="user-profile.html">'
            + '<img src="https://placehold.it/300x300" alt="User name" class="img-circle img-user">'
      + '</a>'
      + '</div>'
      + '<div class="col-xs-9 col-sm-10 info-user">'
          + '<h3><a href="user-profile.html">User Name</a></h3>'
          + '<p><i>2h</i></p>'
      + '</div>'
    + '</div>'
    + '<div class="row">'
       + '<div class="col-sm-8 col-sm-offset-2 data-post">'
            + '<p>Lorem Ipsum Dolor si amet</p>'
            + '<div class="reaction">'
            + '&#x2764; 156 &#x1F603; 54'
            + '</div>'
            + '<div class="comments">'
                + '<ul>'
                    + '<div class="more-comments">View more comments</div>'
                    + '<li><b>User1</b> Lorem Ipsum Dolor si amet</li>'
                    + '<li><b>User2</b> Lorem Ipsum Dolor si amet &#x1F602;</li>'
                + '</ul>'
              + '<form>'
                    + '<input type="text" class="form-control" placeholder="Add a comment">'
              + '</form>'
            + '</div>'
        + '</div>'
  + '</div>'
+ '</div>'

+ '<div class="card-post">'
    + '<div class="row">'
        + '<div class="col-xs-3 col-sm-2">'
            + '<a href="user-profile.html">'
              + '<img src="https://placehold.it/300x300" alt="User name" class="img-circle img-user">'
            + '</a>'
        + '</div>'
        + '<div class="col-xs-9 col-sm-10 info-user">'
            + '<h3><a href="user-profile.html">User Name</a></h3>'
            + '<p><i>2h</i></p>'
        + '</div>'
    + '</div>'
    + '<div class="row">'
        + '<div class=" col-sm-8 col-sm-offset-2 data-post"> <p>Lorem Ipsum Dolor si amet</p>'
            + '<img src="https://placehold.it/600x400" class="img-post">'
            + '<div class="reaction">'
                + '&#x2764; 1234 &#x1F603; 54'
            + '</div>'
            + '<div class="comments">'
                + '<ul>'
                    + '<div class="more-comments">View more comments</div>'
                    + '<li><b>User1</b> Lorem Ipsum Dolor si amet</li>'
                    + '<li><b>User2</b> Lorem Ipsum Dolor si amet &#x1F602;</li>'
                + '</ul>'
                + '<form>'
                    + '<input type="text" class="form-control" placeholder="Add a comment">'
                + '</form>'
            + '</div>'
        + '</div>'
    + '</div>'
+ '</div>'

+ '<div class="card-post">'
    + '<div class="row">'
        + '<div class="col-xs-3 col-sm-2">'
            + '<a href="user-profile.html">'
                + '<img src="https://placehold.it/300x300" alt="User name" class="img-circle img-user">'
            + '</a>'
        + '</div>'
        + '<div class="col-xs-9 col-sm-10 info-user">'
            + '<h3><a href="user-profile.html">User Name</a></h3>'
            + '<p><i>2h</i></p>'
        + '</div>'
    + '</div>'
    + '<div class="row">'
        + '<div class="col-sm-8 col-sm-offset-2 data-post">'
            + '<p>Lorem Ipsum Dolor si amet</p>'
            + '<img src="https://placehold.it/600x400" class="img-post">'
            + '<!-- Video here<video width="100%" height="auto" controls>'
              + '<source src="" type="video/mp4">'
              + 'Your browser does not support the video tag.'
          + '</video>-->'
          + '  <div class="reaction">'
                + '&#x2764; 1234 &#x1F603; 54'
          + '  </div>'
          + '<div class="comments">'
            + '<ul>'
                + '<div class="more-comments">View more comments</div>'
                + '<li><b>User1</b> Lorem Ipsum Dolor si amet</li>'
                + '<li><b>User2</b> Lorem Ipsum Dolor si amet &#x1F602;</li>'
            + '</ul>'
            + '<form>'
                + '<input type="text" class="form-control" placeholder="Add a comment">'
            + '</form>'
          + '</div>'
        + '</div>'
    + '</div>'
+ '</div>';
